global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'minio'
    metrics_path: /minio/v2/metrics/cluster
    bearer_token: minioadmin
    scheme: http
    static_configs:
      - targets: ['minio:9000']
    tls_config:
      insecure_skip_verify: true

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']